### ISSUE TITLE
[Question] connect-kotlin release plan

### ISSUE THREAD

**Issue by vallahaye** [connectrpc/connect-kotlin#233]
Hello everyone,

First of all, thank you for open-sourcing this awesome piece of software. We're currently using the whole Connect stack for a project at work and everything has gone smoothly so far.

That is, until we started using client-only streams in-between our Android app and our back-end (Go). This simply didn't work in all versions up to and including 0.4.0.

The good news is, we've came across @jhump's recent contribution (868181b8939d0d2e4f4ace44665190775a284f51), tested it and it fixed everything 🎉

When can we expect a new version of connect-kotlin including these changes?

Best regards

**Comment by jhump** [comment]
@vallahaye, thanks for inquiring! We do need to cut a release, to capture the fixes to issues found by the [new conformance test suite](https://github.com/connectrpc/conformance).

I'll get started on preparing a release today. We should have it published by the end of this week, if not later today.
