### ISSUE TITLE
Sources can't be downloaded by IDEA Android Studio / Intellij

### ISSUE THREAD

**Issue by jaredsburrows** [connectrpc/connect-kotlin#267]
## Background:

I see that this project is using https://github.com/vanniktech/gradle-maven-publish-plugin. This should publish sources.

I see that `com.connectrpc:connect-kotlin-okhttp:0.6.1` is published on `mavenCentral()` here https://central.sonatype.com/artifact/com.connectrpc/connect-kotlin-okhttp.

I have checked https://search.maven.org/artifact/com.connectrpc/connect-kotlin-okhttp/0.6.1/jar and https://repo1.maven.org/maven2/com/connectrpc/connect-kotlin-okhttp/0.6.1/ and sources **are** published.

See this link https://repo1.maven.org/maven2/com/connectrpc/connect-kotlin-okhttp/0.6.1/connect-kotlin-okhttp-0.6.1-sources.jar.

## Error / Repro:

When I try to use the IDE to manually download the sources I see the following error:

```
Task 'ijDownloadSources18f23d87-b7a' not found in root project 'android-gif-search' and its subprojects.

* Try:
> Run gradle tasks to get a list of available tasks.
> For more on name expansion, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
BUILD FAILED in 163ms
```
or image:

<img width="229" alt="Screenshot 2024-05-09 at 2 58 26 PM" src="https://github.com/connectrpc/connect-kotlin/assets/1739848/b2707046-5dde-4ade-a98f-937c14ab4f2b">

<img width="1423" alt="Screenshot 2024-05-09 at 2 58 07 PM" src="https://github.com/connectrpc/connect-kotlin/assets/1739848/d4663d51-38ff-4609-bfcb-98c85978c3e4">

I see the same when stepping into the code for debugging and I click on "Download Source":

<img width="884" alt="Screenshot 2024-05-09 at 2 59 57 PM" src="https://github.com/connectrpc/connect-kotlin/assets/1739848/05209d4b-dfc6-4b33-b451-75af48f1da7b">
<img width="1479" alt="Screenshot 2024-05-09 at 3 00 04 PM" src="https://github.com/connectrpc/connect-kotlin/assets/1739848/b3ddbbae-eba6-4ae7-bcfb-0d93fc92a7ef">

## Going forward:
Is this an IDE problem or the way the sources are being published?

**Comment by jhump** [comment]
Closing since this appears to be an IDE issue, not something with connect-kotlin.
