### ISSUE TITLE
Buf build buf.gen.yaml instructions for connectrpc/kotlin don't mention protocolbuffers version

### ISSUE THREAD

**Issue by q42jaap** [connectrpc/connect-kotlin#299]
https://buf.build/connectrpc/kotlin?version=v0.6.1 
The docs for connectrpc/kotlin don't mention the version of buf.build/protocolbuffers/kotlin this depends on.
for 0.6.1 it should be buf.build/protocolbuffers/kotlin:26.1
for 0.7.0 it should be buf.build/protocolbuffers/kotlin:27.2

If this could be added to buf.build this would be very helpful in avoiding mistakes.

Also, the release notes of 0.7.0 don't mention the protocolbuffers version.

The runtime error protocolbuffers gives is easy enough to understand, but it still took us some time and caused a bit of confusion.

**Comment by pkwarren** [comment]
I'll log a ticket for the BSR around plugin version dependencies, however the connectrpc org isn't a great place to track these. In the meantime I'll close this ticket and let you know if we should create it in another repo.

> Also, the release notes of 0.7.0 don't mention the protocolbuffers version.

See under "Other Changes": https://github.com/connectrpc/connect-kotlin/releases/tag/v0.7.0

**Comment by pkwarren** [comment]
@q42jaap - We've updated the BSR to pin the version of plugin dependencies in the example `buf.gen.yaml` files that should hopefully avoid issues like this in the future: https://buf.build/connectrpc/kotlin?version=v0.7.0

<img width="467" alt="image" src="https://github.com/user-attachments/assets/3bc47ba2-8804-4b72-aaa8-9497e1399ce5">
